AWSTemplateFormatVersion: 2010-09-09
Description: "Creates a central S3 Bucket for Centralised CloudTrail Logging"
Parameters:
  AWSConfigS3Bucket:
    Type: String
    Description: "Production account"
Resources:
  # Build AWS Config Recorder
  ConfigRecorder:
    Type: "AWS::Config::ConfigurationRecorder"
    Properties:
      Name: "ConfigRecoder"
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true
      RoleARN: !GetAtt
        - AWSIAM
        - Arn

  # Build IAM Role for Config
  AWSIAM:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSConfigRole"
      Path: /
      Policies:
        - PolicyName: S3-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                Resource: !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref AWSConfigS3Bucket
                    - /AWSLogs/
                    - !Ref "AWS::AccountId"
                    - /*
                Condition:
                  StringLike:
                    "s3:x-amz-acl": bucket-owner-full-control
              - Effect: Allow
                Action:
                  - "s3:GetBucketAcl"
                Resource: !Join
                  - ""
                  - - "arn:aws:s3:::"
                    - !Ref AWSConfigS3Bucket

  # Create Config Delivery Channel
  DeliveryChannel:
    Type: "AWS::Config::DeliveryChannel"
    Properties:
      S3BucketName: !Ref AWSConfigS3Bucket

Outputs:
  AWSIAM:
    Description: "IAM Role for Config"
    Value:
      Ref: "AWSIAM"
  AWSConfigS3Bucket:
    Description: "Encrypted S3 Bucket for Config Logs"
    Value:
      Ref: "AWSConfigS3Bucket"
  ConfigRecorder:
    Description: "Config Recorder"
    Value:
      Ref: "ConfigRecorder"
  DeliveryChannel:
    Description: "Config Delivery Channel"
    Value:
      Ref: "DeliveryChannel"
