# CloudTrail for AWS Organization
# Copyright [2018] [Phil Chen]
# Modified by Ben Fellows (2023) for Organizations use.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

AWSTemplateFormatVersion: 2010-09-09

Description: "The AWS CloudFormation template creates KMS encryption keys for CloudTrail and S3, an encrypted S3 bucket, and enables CloudTrail for the account"

Resources:
  # Create KMS CloudTrail encryption key
  TopsCloudTrailKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-cloudtrail
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow CloudTrail to encrypt logs
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: "kms:GenerateDataKey*"
            Resource: "*"
            Condition:
              StringLike:
                "kms:EncryptionContext:aws:cloudtrail:arn": !Sub "arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*"
          - Sid: Allow CloudTrail to describe key
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: "kms:DescribeKey"
            Resource: "*"
          - Sid: Allow principals in the account to decrypt log files
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "kms:Decrypt"
              - "kms:ReEncryptFrom"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub "${AWS::AccountId}"
              StringLike:
                "kms:EncryptionContext:aws:cloudtrail:arn": !Sub "arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*"
          - Sid: Allow alias creation during setup
            Effect: Allow
            Principal:
              AWS: "*"
            Action: "kms:CreateAlias"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:ViaService": ec2.region.amazonaws.com
                "kms:CallerAccount": !Sub "${AWS::AccountId}"
          - Sid: Enable cross account log decryption
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - "kms:Decrypt"
              - "kms:ReEncryptFrom"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub "${AWS::AccountId}"
              StringLike:
                "kms:EncryptionContext:aws:cloudtrail:arn": !Sub "arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*"
      Tags:
        - Key: "Name"
          Value: "TopsCloudTrailKey"
        - Key: "Environment"
          Value: "Audit"
        - Key: "CreatedBy"
          Value: "tops"

  TopsCloudTrailKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/cloudtrail
      TargetKeyId:
        Ref: TopsCloudTrailKey

  # Create KMS CloudTrail S3 bucket encryption key
  Topss3CloudTrailKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-cloudtrails3
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ""
                - - "arn:aws:iam::"
                  - !Ref "AWS::AccountId"
                  - ":root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Allow VPC Flow Logs to use the key
            Effect: Allow
            Principal:
              Service:
                - delivery.logs.amazonaws.com
            Action: "kms:GenerateDataKey*"
            Resource: "*"
          - Sid: Allow Cloudtrail to use the key
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: "kms:GenerateDataKey*"
            Resource: "*"
          - Sid: Allow CloudTrail to describe key
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: "kms:DescribeKey"
            Resource: "*"
      Tags:
        - Key: "Name"
          Value: "TopsCloudTrailKey"
        - Key: "Environment"
          Value: "Audit"
        - Key: "CreatedBy"
          Value: "tops"

  Topss3CloudTrailKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/cloudtrails3
      TargetKeyId:
        Ref: Topss3CloudTrailKey

  # Create CloudTrail encrypted S3 bucket for storage
  TopsCloudTrailS3Bucket:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    DependsOn:
      - Topss3CloudTrailKey
      - Topss3CloudTrailKeyAlias
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${Topss3CloudTrailKeyAlias}"
      Tags:
        - Key: "Name"
          Value: "TopsCloudTrailS3Bucket"
        - Key: "Environment"
          Value: "Audit"
        - Key: "CreatedBy"
          Value: "tops"

  TopsCloudTrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TopsCloudTrailS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AWSCloudTrailAclCheck"
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub arn:aws:s3:::${TopsCloudTrailS3Bucket}
          - Sid: "AWSCloudTrailWrite"
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub arn:aws:s3:::${TopsCloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Sid: "AWSCloudTrailReadOnlyAccess"
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${TopsCloudTrailS3Bucket}/AWSLogs/${AWS::AccountId}/*

  # Enable CloudTrail
  TopsCloudTrail:
    DependsOn:
      - TopsCloudTrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      IsOrganizationTrail: true
      S3BucketName: !Ref TopsCloudTrailS3Bucket
      IsLogging: true
      KMSKeyId: !GetAtt TopsCloudTrailKey.Arn
      Tags:
        - Key: "Name"
          Value: "TopsCloudTrail"
        - Key: "Environment"
          Value: "Audit"
        - Key: "CreatedBy"
          Value: "tops"

Outputs:
  CloudTrailKMSKeyAlias:
    Description: "CloudTrail KMS Key Alias"
    Value:
      Ref: "TopsCloudTrailKeyAlias"
  S3KMSKeyAlias:
    Description: "S3 KMS Key Alias"
    Value:
      Ref: "Topss3CloudTrailKeyAlias"
  CloudTrailS3Bucket:
    Description: "Encrypted S3 Bucket for CloudTrail Logs"
    Value:
      Ref: "TopsCloudTrailS3Bucket"
  CloudTrailS3BucketPolicy:
    Description: "S3 Bucket Policy for CloudTrail Logs"
    Value:
      Ref: "TopsCloudTrailBucketPolicy"
  CloudTrail:
    Description: "CloudTrail"
    Value:
      Ref: "TopsCloudTrail"
