#Allow access to another AWS account to run CloudFormation StackSets in this account

AWSTemplateFormatVersion: 2010-09-09
Description: Configure the AWSCloudFormationStackSetExecutionRole to enable use of your account as a target account in AWS CloudFormation StackSets.

Parameters:
  AdministratorAccountId:
    Type: String
    Description: AWS Account Id of the administrator account (the account in which StackSets will be created).
    MaxLength: 12
    MinLength: 12
  ExecutionRoleName:
    Type: String
    Default: AWSCloudFormationStackSetExecutionRole
    Description: "The name of the execution role. Defaults to 'AWSCloudFormationStackSetExecutionRole'."

Resources:
  TopsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ExecutionRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
  TopsAllowCloudFormation:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "TopsConfigDeTopsAllowCloudFormationliveryChannel"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "cloudformation:*"
            Resource: "*"
      Roles:
        - !Ref TopsExecutionRole
  TopsAllowConfig:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "TopsConfigDeliveryChannel"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "config:*"
            Resource: "*"
      Roles:
        - !Ref TopsExecutionRole
  TopsAllowSecurityHub:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "TopsConfigDeliveryChannel"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "securityhub:*"
            Resource: "*"
      Roles:
        - !Ref TopsExecutionRole
