AWSTemplateFormatVersion: "2010-09-09"
Description: Teemops DynamoDB Template
Parameters:
  AppId:
    Description: Teemops App ID
    Type: String
  CustomerId:
    Description: Teemops Customer ID
    Type: String
  TableName:
    Description: Table Name
    Type: String
  PrimaryKey:
    Description: Primary Key
    Type: String
Resources:
  TopsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - 
          AttributeName: notifyid
          AttributeType: N
        - 
          AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - 
          AttributeName: notifyid
          KeyType: HASH
        - 
          AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  