AWSTemplateFormatVersion: "2010-09-09"
Description: Teemops Aurora Initial Launch Template
Parameters:
  AppId:
    Description: Teemops App ID
    Type: String
  AppName:
    Description: Teemops App Name
    Type: String
  CustomerId:
    Description: Teemops Customer ID
    Type: String
  ClusterEngine:
    Description: Database Engine
    Type: String
    AllowedValues: ["aurora", "aurora-mysql", "aurora-postgresql"]
  DBEngineMode:
    Description: Mode (Serverless, provisioned, parallelquery, global or multimaster)
    Type: String
    AllowedValues: ["provisioned", "serverless", "parallelquery", "global", "multimaster"]
  ClusterName:
    Description: Cluster Name
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid Cluster Name
  DBName:
    Description: Name of default database
    Type: String
  DBUser:
    Description: Database User
    Type: String
  DBPassword:
    Description: Database Password
    Type: String
    NoEcho: true
    MinLength: 5
    MaxLength: 30
    AllowedPattern: ^[a-zA-Z0-9]*$
  Subnets:
    Description: Select 1 or more Subnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Description: Select 1 or more Security Groups
    Type: List<AWS::EC2::SecurityGroup::Id>
# Conditions:
#   ConditionPublicIp: !Equals [!Ref HasPublicIp, "true"]
Resources:
  TopsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: "Auto generated by Teemops Cloudformation template"
      SubnetIds: !Ref Subnets
  TopsDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      CopyTagsToSnapshot: true
      Engine: !Ref ClusterEngine
      EngineMode: !Ref DBEngineMode
      DatabaseName: !Ref DBName
      DBClusterIdentifier: !Ref ClusterName
      DBSubnetGroupName: !Ref TopsDBSubnetGroup
      VpcSecurityGroupIds: !Ref SecurityGroups
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Ref AppName
        - Key: topsid
          Value: !Ref AppId
        - Key: topscustomerid
          Value: !Ref CustomerId
Outputs:
  InstanceId:
    Description: ClusterId
    Value: !Ref TopsDBCluster
  DNSHostname:
    Description: DB Cluster DNS Name
    Value:
      Fn::GetAtt:
        - TopsDBCluster
        - Endpoint.Address
