AWSTemplateFormatVersion: "2010-09-09"
Description: Teemops RDS Initial Launch Template
Parameters:
  InstanceType:
    Description: Amazon RDS instance type
    Type: String
  RootVolumeSize:
    Description: Disk Volume Size in GB
    Type: Number
  AppId:
    Description: Teemops App ID
    Type: String
  AppName:
    Description: Teemops App Name
    Type: String
  CustomerId:
    Description: Teemops Customer ID
    Type: String
  DBEngine:
    Description: Database Engine
    Type: String
    AllowedValues: ["mariadb", "mysql", "oracle-ee", "oracle-se2", "oracle-se1", "oracle-se", "postgres", "sqlserver-ee", "sqlserver-se", "sqlserver-ex", "sqlserver-web"]
  DBName:
    Description: Database Name
    Type: String
  DBUser:
    Description: Database User
    Type: String
  DBPassword:
    Description: Database Password
    Type: String
    NoEcho: true
    MinLength: 5
    MaxLength: 30
    AllowedPattern: ^[a-zA-Z0-9]*$
  Subnets:
    Description: Select 1 or more Subnets
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroups:
    Description: Select 1 or more Security Groups
    Type: List<AWS::EC2::SecurityGroup::Id>
  HasPublicIp:
    Description: Public Access
    Type: String
    AllowedValues: ["true", "false"]
  HasMultiAZ:
    Description: MultiAZ Failover
    Type: String
    AllowedValues: ["true", "false"]
# Conditions:
#   ConditionPublicIp: !Equals [!Ref HasPublicIp, "true"]
Resources:
  TopsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: "Auto generated by Teemops Cloudformation template"
      SubnetIds: !Ref Subnets
  TopsRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref RootVolumeSize
      CopyTagsToSnapshot: true
      Engine: !Ref DBEngine
      DBInstanceClass: !Ref InstanceType
      DBInstanceIdentifier: !Ref DBName
      DBSubnetGroupName: !Ref TopsDBSubnetGroup
      VPCSecurityGroups: !Ref SecurityGroups
      PubliclyAccessible: !Ref HasPublicIp
      StorageType: gp2
      MultiAZ: !Ref HasMultiAZ
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Ref AppName
        - Key: topsid
          Value: !Ref AppId
        - Key: topscustomerid
          Value: !Ref CustomerId
Outputs:
  InstanceId:
    Description: RDS InstanceId
    Value: !Ref TopsRDS
  DNSHostname:
    Description: RDS DNS Name
    Value:
      Fn::GetAtt:
        - TopsRDS
        - Endpoint.Address
