#https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/quickcreate?templateUrl=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Ftemplates.teemops.com%2Fteem.admin.share.cfn.yaml&stackName=ca-teem
#https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/quickcreate?templateUrl=https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Ftemplates.teemops.com%2Fteem.admin.share.cfn.yaml&stackName=ca-teem
Resources:
  TeemAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: KiwiTeemAdmin
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              AWS: "arn:aws:iam::163057906376:root"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - "*"
                Effect: Allow
                Resource: "*"
          PolicyName: TeemAdminPolicy
