Resources:
  TeemAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KiwiTeamAdminBen"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              AWS: "arn:aws:iam::163057906376:user/benteem"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /
  TeemAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref TeemAdminRole
      PolicyName: "CloudOpsAdmin"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AdminFull"
            Effect: "Allow"
            Action:
              - "*"
            Resource: "*"
