Resources:
  TeemAdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KiwiTeamAdmin"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              AWS: "arn:aws:iam::163057906376:root"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      Path: /
  TeemAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref TeemAdminRole
      PolicyName: "CloudOpsAdmin"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AdminFull"
            Effect: "Allow"
            Action:
              - "*"
            Resource: "*"
  TeemAdminDenyPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref TeemAdminRole
      PolicyName: "CloudOpsAdmin"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "DenyIAM"
            Effect: "Deny"
            Action:
              - "iam:CreateGroup"
              - "iam:DeleteGroup"
              - "iam:UpdateUser"
              - "iam:AttachUserPolicy"
              - "iam:DeleteUserPolicy"
              - "iam:UpdateGroup"
              - "iam:DeleteRole"
              - "iam:DeleteSSHPublicKey"
              - "iam:CreateVirtualMFADevice"
              - "iam:DeleteUser"
              - "iam:CreateUser"
              - "iam:RemoveUserFromGroup"
              - "iam:AddUserToGroup"
              - "iam:DeleteSigningCertificate"
              - "iam:AttachGroupPolicy"
              - "iam:PutUserPolicy"
              - "iam:DeleteServerCertificate"
              - "iam:DetachGroupPolicy"
              - "iam:DeleteServiceLinkedRole"
              - "iam:DeleteAccountAlias"
              - "iam:DetachUserPolicy"
              - "iam:DeleteServiceSpecificCredential"
              - "iam:DeleteSAMLProvider"
              - "iam:PutGroupPolicy"
            Resource: "*"
