---

#install php 8.0 packages
packages:
  - composer
  - mysql-client
  - php8.0
  - php8.0-cli
  - php8.0-common
  - php8.0-curl
  - php8.0-dev
  - php8.0-gd
  - php8.0-intl
  - php8.0-mbstring
  - php8.0-mysql
  - php8.0-opcache
  - php8.0-readline
  - php8.0-xml
  - php8.0-zip
  - php8.0-bcmath
  - php8.0-bz2
  - php8.0-fpm
  - php8.0-memcached
  - php8.0-tidy
  - php8.0-xmlrpc
  - php8.0-xsl
  - php8.0-oauth
  - php8.0-pgsql
  - php8.0-yaml
  - php8.0-mcrypt
  - libapache2-mod-php8.0
