AWSTemplateFormatVersion: '2010-09-09'
Description: Teemops S3 + CloudFront + SSL Cert
Parameters:
  HostedZone:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  DomainAlias:
    Type: String
    Description: The DNS name of an existing Amazon Route 53 hosted zone
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
  SSLArn:
    Type: String
Mappings:
  Region2S3WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
    us-east-2:
      Suffix: .s3-website-us-east-2.amazonaws.com
    us-east-3:
      Suffix: .s3-website-us-east-3.amazonaws.com
    us-west-1:
      Suffix: .s3-website-us-west-1.amazonaws.com
    us-west-2:
      Suffix: .s3-website-us-west-2.amazonaws.com
    us-west-3:
      Suffix: .s3-website-us-west-3.amazonaws.com
    eu-west-1:
      Suffix: .s3-website-eu-west-1.amazonaws.com
    eu-west-2:
      Suffix: .s3-website.eu-west-2.amazonaws.com
    eu-west-3:
      Suffix: .s3-website.eu-west-3.amazonaws.com
    ap-northeast-1:
      Suffix: .s3-website-ap-northeast-1.amazonaws.com
    ap-northeast-2:
      Suffix: .s3-website.ap-northeast-2.amazonaws.com
    ap-northeast-3:
      Suffix: .s3-website.ap-northeast-3.amazonaws.com
    ap-southeast-1:
      Suffix: .s3-website-ap-southeast-1.amazonaws.com
    ap-southeast-2:
      Suffix: .s3-website-ap-southeast-2.amazonaws.com
    ap-southeast-3:
      Suffix: .s3-website-ap-southeast-3.amazonaws.com
    ap-south-1:
      Suffix: .s3-website-ap-south-1.amazonaws.com
    ap-south-2:
      Suffix: .s3-website-ap-south-2.amazonaws.com
    sa-east-1:
      Suffix: .s3-website-sa-east-1.amazonaws.com
    sa-east-2:
      Suffix: .s3-website-sa-east-2.amazonaws.com
    cn-north-1:
      Suffix: .s3-website.cn-north-1.amazonaws.com.cn
    cn-northwest-1:
      Suffix: .s3-website.cn-northwest-1.amazonaws.com.cn
    eu-central-1:
      Suffix: .s3-website.eu-central-1.amazonaws.com
    eu-central-2:
      Suffix: .s3-website.eu-central-2.amazonaws.com
    eu-south-1:
      Suffix: .s3-website.eu-south-1.amazonaws.com
    eu-north-1:
      Suffix: .s3-website.eu-north-1.amazonaws.com
    me-south-1:
      Suffix: .s3-website.me-south-1.amazonaws.com
    ca-central-1:
      Suffix: .s3-website.ca-central-1.amazonaws.com
    af-south-1:
      Suffix: .s3-website.af-south-1.amazonaws.com
    ap-east-1:
      Suffix: .s3-website.ap-east-1.amazonaws.com
    us-gov-east-1:
      Suffix: .s3-website.us-gov-east-1.amazonaws.com
    us-gov-west-1:
      Suffix: .s3-website-us-gov-west-1.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CDN for S3-backed website
        Aliases:
        - !Ref 'DomainAlias'
        Enabled: 'true'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: only-origin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        ViewerCertificate: 
          AcmCertificateArn: !Ref SSLArn
          SslSupportMethod: sni-only
        Origins:
        - CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
          DomainName: !Join ['', [!Ref 'S3BucketForWebsiteContent', !FindInMap [Region2S3WebsiteSuffix,
                !Ref 'AWS::Region', Suffix]]]
          Id: only-origin
  WebsiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Join ['', [!Ref 'HostedZone', .]]
      Comment: CNAME redirect custom name to CloudFront distribution
      Name: !Join ['', [!Ref 'AWS::StackName', !Ref 'AWS::AccountId', ., !Ref 'AWS::Region',
          ., !Ref 'HostedZone']]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
      - !GetAtt [WebsiteCDN, DomainName]
Outputs:
  WebsiteURL:
    Value: !Join ['', ['http://', !Ref 'WebsiteDNSName']]
    Description: The URL of the newly created website
  BucketName:
    Value: !Ref 'S3BucketForWebsiteContent'
    Description: Name of S3 bucket to hold website content